### ISSUE TITLE
assert in flutter_hooks fails

### ISSUE THREAD

**Issue by arturaz** [rrousselGit/flutter_hooks#133]
Version:  **flutter_hooks: 0.9.0**

I get an error in runtime:
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building FunctionalWidget(dirty, state: _HookWidgetState#d8e23):
_currentHook.current.hook.runtimeType=_StateHook<GlobalKey<FormState>>
hook.runtimeType=_StateHook<int>
'package:flutter_hooks/src/framework.dart':
Failed assertion: line 477 pos 12: '_currentHook.current.hook.runtimeType == hook.runtimeType'

The relevant error-causing widget was: 
  FunctionalWidget file:///E:/work/flutter/zowo/packages/client/lib/main.dart:60:6
When the exception was thrown, this was the stack: 
#2      HookElement._debugTypesAreRight (package:flutter_hooks/src/framework.dart:477:12)
#3      HookElement._use (package:flutter_hooks/src/framework.dart:432:16)
#4      Hook.use (package:flutter_hooks/src/framework.dart:136:40)
#5      useState (package:flutter_hooks/src/primitives.dart:206:15)
#6      MyHomePage.<anonymous closure> (package:zowo/main.dart:61:19)
...
```

I modified **framework.dart** to include more details:

```
  bool _debugTypesAreRight(Hook hook) {
    assert(_currentHook.current.hook.runtimeType == hook.runtimeType,
    "_currentHook.current.hook.runtimeType=${_currentHook.current.hook.runtimeType}\nhook.runtimeType=${hook.runtimeType}");
    return true;
  }
```

I am using a lightweight function-to-widget wrapper:

```
import 'package:flutter/widgets.dart';
import 'package:flutter_hooks/flutter_hooks.dart';

class FunctionalWidget extends HookWidget {
  final Widget Function(BuildContext) buildWidget;

  const FunctionalWidget(Key key, this.buildWidget) : super(key: key);

  @override
  Widget build(BuildContext context) => buildWidget(context);
}
```

And my app looks like this:

```
// ignore: non_constant_identifier_names
FunctionalWidget MyApp() => FunctionalWidget(null, (context) {
  final store = useReducer<AppState, AppEvent>(
    (state, event) => event == null ? state : event.apply(state),
    initialState: AppState.initial()
  );
  final authState = useState(const Option<FirebaseUser>.none());
  useEffect(() => FirebaseAuth.instance.onAuthStateChanged.listen((maybeUser) {
    authState.value = Option.check(maybeUser);
  }).cancel);

  return MaterialApp(
    title: 'Flutter Demo',
    theme: ThemeData(primarySwatch: Colors.blue),
    home: authState.value.isSome ? MyHomePage('Flutter Demo', store) : SignInScreen(),
  );
});


// ignore: non_constant_identifier_names
Widget SignInScreen({
  void Function(FirebaseUser user) onAuth, Key key
}) => FunctionalWidget(key, (context) {
  final formKey = useState(GlobalKey<FormState>());
  final phoneCtrl = useTextEditingController();
  final codeCtrl = useTextEditingController();
  final error = useState(const Option<String>.none());
  final loading = useState(false);
  final maybeVerificationId = useState(const Option<String>.none());
  final auth = FirebaseAuth.instance;

  Future<void> authWithCredential(AuthCredential credential) async {
    try {
      final authResult = await auth.signInWithCredential(credential);
      if (authResult.user != null) {
        Log.d("Auth successful.");
        if (onAuth != null) onAuth(authResult.user);
      }
      else {
        Log.d("Auth failed: $authResult");
      }
    }
    on Exception catch (err) {
      Log.e("Auth errored", err);
      error.value = Some(err.toString());
    }
    finally {
      loading.value = false;
    }
  }

  // https://medium.com/@fayaz07/firebase-phone-auth-with-flutter-db7e934ef46f
  void onPhoneEntered(String phone) {
    error.value = const Option.none();
    loading.value = true;
    maybeVerificationId.value = const Option.none();

    auth.verifyPhoneNumber(
      phoneNumber: phone, timeout: const Duration(seconds: 30),
      verificationCompleted: (phoneAuthCredential) async {
        Log.d("verificationCompleted: $phoneAuthCredential");
        await authWithCredential(phoneAuthCredential);
      },
      verificationFailed: (err) {
        final errorStr = "${err.message} (${err.code})";
        Log.d("verificationFailed: $errorStr");
        error.value = Some(errorStr);
        maybeVerificationId.value = const Option.none();
        loading.value = false;
      },
      codeSent: (verificationId, [forceResendingToken]) {
        Log.d("codeSent: forceResendingToken=$forceResendingToken, verificationId=$verificationId");
        maybeVerificationId.value = Some(verificationId);
      },
      codeAutoRetrievalTimeout: null,
    );
  }

  Future<void> onCodeEntered({@required String verificationId, @required String code}) async {
    final credential = PhoneAuthProvider.getCredential(verificationId: verificationId, smsCode: code);
    await authWithCredential(credential);
  }

  return Scaffold(
    appBar: AppBar(title: const Text("Login")),
    body: Form(
      key: formKey.value,
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          if (error.value.isSome) Text(
            error.value.unsafeGet,
            style: TextStyle(color: Theme.of(context).errorColor),
          ),
          maybeVerificationId.value.fold(
            () => TextFormField(
              controller: phoneCtrl,
              decoration: const InputDecoration(labelText: "Phone"),
              keyboardType: TextInputType.phone,
              validator: (s) => s.trim().isEmpty ? "Enter your phone" : null,
            ),
            (verificationId) => TextFormField(
              controller: codeCtrl,
              decoration: const InputDecoration(labelText: "Code"),
              keyboardType: TextInputType.number,
              validator: (s) => s.trim().isEmpty ? "Enter your code" : null,
            )
          ),
          RaisedButton(
            onPressed: loading.value ? null : () {
              if (formKey.value.currentState.validate()) {
                maybeVerificationId.value.fold(
                  () => onPhoneEntered(phoneCtrl.text),
                  (verificationId) { onCodeEntered(verificationId: verificationId, code: codeCtrl.text); }
                );
              }
            },
            child: Row(children: <Widget>[
              if (loading.value) const CircularProgressIndicator(),
              const Text("Submit")
            ]),
          )
        ],
      ),
    ),
  );
});

// ignore: non_constant_identifier_names
FunctionalWidget MyHomePage(
  String title, Store<AppState, AppEvent> appState, {Key key}
) => FunctionalWidget(key, (context) {
  // ***** THIS FAILS THE ASSERTION *****
  final counter = useState(0);

  Future<Option<CategoryData>> showCategorySelect() =>
    showDialog<CategoryData>(
      context: context,
      builder: (context) => Dialog(
        insetPadding: const EdgeInsets.symmetric(horizontal: 20, vertical: 120),
        child: Center(child: CategorySelect(
          appState.state.categories,
          onTap: (category) {
            Navigator.pop(context, category);
          }
        )),
      )
    ).then((value) => Option.check(value));

  return TimelineScreen(TimelineData(
    data: BuiltMap.of({
      YearAndMonth.a(2020, Month.May): BuiltMap.of({}),
      YearAndMonth.a(2020, Month.April): BuiltMap.of({}),
      YearAndMonth.a(2020, Month.January): BuiltMap.of({}),
      YearAndMonth.a(2020, Month.February): BuiltMap.of({}),
      YearAndMonth.a(2019, Month.May): BuiltMap.of({}),
      YearAndMonth.a(2019, Month.April): BuiltMap.of({}),
      YearAndMonth.a(2019, Month.January): BuiltMap.of({}),
      YearAndMonth.a(2019, Month.February): BuiltMap.of({}),
    })
  ));
});
```

Not sure what is happening. Any direction would be appreciated.

Edit:

Changing one widget to class based implementation removes the error.

```
class MyHomePage2 extends HookWidget {
  final String title;
  final Store<AppState, AppEvent> appState;

  const MyHomePage2(this.title, this.appState, {Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final counter = useState(0);

    Future<Option<CategoryData>> showCategorySelect() =>
      showDialog<CategoryData>(
        context: context,
        builder: (context) => Dialog(
          insetPadding: const EdgeInsets.symmetric(horizontal: 20, vertical: 120),
          child: Center(child: CategorySelect(
            appState.state.categories,
            onTap: (category) {
              Navigator.pop(context, category);
            }
          )),
        )
      ).then((value) => Option.check(value));

    return TimelineScreen(TimelineData(
      data: BuiltMap.of({
        YearAndMonth.a(2020, Month.May): BuiltMap.of({}),
        YearAndMonth.a(2020, Month.April): BuiltMap.of({}),
        YearAndMonth.a(2020, Month.January): BuiltMap.of({}),
        YearAndMonth.a(2020, Month.February): BuiltMap.of({}),
        YearAndMonth.a(2019, Month.May): BuiltMap.of({}),
        YearAndMonth.a(2019, Month.April): BuiltMap.of({}),
        YearAndMonth.a(2019, Month.January): BuiltMap.of({}),
        YearAndMonth.a(2019, Month.February): BuiltMap.of({}),
      })
    ));
  }
}
```

I suppose you are doing some type checking and because all widgets of FunctionalWidget have the same type things break.

**Comment by rrousselGit** [comment]
The problem is your lightweight function as class.

Remove that and it will work.

**Comment by arturaz** [comment]
But why does it fail? Can you shine a bit more light on the implementation
details?

**Comment by rrousselGit** [comment]
Each widget needs to have a unique `runtimeType`.
With functions, that is not the case

This is what causes your issue.

**Comment by arturaz** [comment]
Understood. I think that would be a nice amendment to the rules block in
the readme.

I can write it and submit a PR. Is that OK with you?

**Comment by rrousselGit** [comment]
This is not caused by hooks, but Flutter

It is something that impacts all widgets
