### ISSUE TITLE
Provide better error message if hook is used outside HookWidget

### ISSUE THREAD

**Issue by degroote22** [rrousselGit/flutter_hooks#24]
First of all I'd like to thank you for this lib. It's awesome and I love it!!!

I'd like to request a better error message on [this assertion](https://github.com/rrousselGit/flutter_hooks/blob/master/lib/src/framework.dart#L351) because I've spent the last hour trying to debug my app to find that I was using a hook outside a HookWidget.

I'm having trouble finding out how to write a better error message because I'd like to know the name of the class that created the trouble so that the error message could be something like:

`
Error: The class _MyClassName doesn't extend HookWidget and is using a hook.
`

Thanks 👍

**Comment by rrousselGit** [comment]
I don't think you pointed to the right assert. This one is for when you changed the type of the hook.

The issue you described is the following assert: https://github.com/rrousselGit/flutter_hooks/blob/master/lib/src/framework.dart#L124

which clearly states 
> `Hook.use` can only be called from the build method of HookWidget

**Comment by rrousselGit** [comment]
I would love to add in the message the name of the class who used it. But it is technically not possible since this issue happens when hooks don't know _which_ class called `Hook.use`

The most you can get out of this is by looking at the stacktrace, which should contain the name of the caller.

**Comment by degroote22** [comment]
@rrousselGit, that's not the case.
I'm using v0.2.0 and changed a HookWidget to StatelessWidget and got this on the stacktrace.

```
I/flutter (22968): 'package:flutter_hooks/src/framework.dart': Failed assertion: line 354 pos 14:
I/flutter (22968): '_currentHook.current?.hook?.runtimeType == hook.runtimeType': is not true.
I/flutter (22968):
I/flutter (22968): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (22968): more information in this error message to help you determine and fix the underlying cause.
I/flutter (22968): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (22968):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (22968):
I/flutter (22968): When the exception was thrown, this was the stack:
I/flutter (22968): #2      HookElement._use (package:flutter_hooks/src/framework.dart:354:14)
I/flutter (22968): #3      Hook.use (package:flutter_hooks/src/framework.dart:129:40)
I/flutter (22968): #4      useState (package:flutter_hooks/src/hooks.dart:205:15)
I/flutter (22968): #5      _EditingKmBar.build (package:mob/searchpage/view.dart:129:17)
I/flutter (22968): #6      StatelessElement.build (package:flutter/src/widgets/framework.dart:3774:28)
I/flutter (22968): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter (22968): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (22968): #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (22968): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (22968): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (22968): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (22968): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (22968): #14     HookElement.performRebuild (package:flutter_hooks/src/framework.dart:258:11)
I/flutter (22968): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (22968): #16     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
I/flutter (22968): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
I/flutter (22968): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (22968): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (22968): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (22968): #21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (22968): #22     _invoke (dart:ui/hooks.dart:154:13)
I/flutter (22968): #23     _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter (22968): (elided 2 frames from class _AssertionError)
```

Maybe the assertion I linked above is being triggered before the one with the correct message...

Thanks for the attention 👍

**Comment by rrousselGit** [comment]
Can you provide a minimal example to reproduce this error?

When I do the same thing, I get a 

> type `MyWidget` is not a subtype of `HookWidget` in typecast

**Comment by rrousselGit** [comment]
@degroote22 Any update on this issue? I cannot progress on this without being able to reproduce the error

**Comment by degroote22** [comment]
I'm sorry for the delay. I'd taken some time off celebrating the new year :)

I'll provide you with a reproduction tomorrow!

**Comment by degroote22** [comment]
I'm trying to reproduce with 0.2.1 and it won't happen anymore 👍 

I'm closing this, and once again, I'm sorry for the delay.
