### ISSUE TITLE
Why list not updating?

### ISSUE THREAD

**Issue by tony123S** [rrousselGit/flutter_hooks#401]
Wonder why `ListView` not updating after `vehicleItems` is added into the list? The list only updated after hot reload. 
```
class EditScreen extends HookWidget {
  final ValueNotifier<List<VehicleItems>> list; // list passed from previous page

  const EditScreen(this.list, {super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
          backgroundColor: AppTheme.light.colorScheme.primary,
          onPressed: () {
            Navigator.pushNamed(context, ABCRoutes.createScreen)
                .then(((onValue) {
              if (onValue is VehicleItems) {
                list.value = [...list.value, onValue];  // add to list
              }
            }));
          },
          child: const Icon(
            Icons.add,
            color: Colors.white,
          )),
      appBar: AppBar(
          iconTheme: const IconThemeData(color: Colors.white),
          backgroundColor: AppTheme.light.colorScheme.primary,
          title: Text(
            'vehicles'.tr(),
            style: const TextStyle(color: Colors.white),
          ),
          actions: const []),
      body: _showBody(list),
    );
  }

  Widget _showBody(ValueNotifier<List<VehicleItems>> list) {
    return ListView.separated(
        padding: EdgeInsets.zero,
        shrinkWrap: true,
        separatorBuilder: (context, index) => Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20),
            child: Container(
              color: Colors.grey.shade200,
              height: 1,
            )),
        itemCount: list.value.length,
        itemBuilder: (context, index) {
          final items = list.value[index];
          return InkWell(
              onTap: () {},
              child: ListItemPadding(
                child: VehicleItem(items),
              ));
        });
  }
}
```

**Comment by rrousselGit** [comment]
You're not listening to the ValueNotifier

Use useValueListenable(list);

**Comment by tony123S** [comment]
> You're not listening to the ValueNotifier
> 
> Use useValueListenable(list);

Sorry, I have edited my post to make it clearer. I'm using useState in Page A.

**Comment by rrousselGit** [comment]
My answer doesn't change. Use useValueListenable in EditScreen :)

**Comment by tony123S** [comment]
> list.value = [...list.value..add(onValue)];

Error after added  useValueListenable
```

E/flutter (23009): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter_hooks/src/framework.dart': Failed assertion: line 133 pos 12: 'HookElement._currentHookElement != null': Hooks can only be called from the build method of a widget that mix-in `Hooks`.
E/flutter (23009): 
E/flutter (23009): Hooks should only be called within the build method of a widget.
E/flutter (23009): Calling them outside of build method leads to an unstable state and is therefore prohibited.
E/flutter (23009): 
E/flutter (23009): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter (23009): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter (23009): #2      Hook.use (package:flutter_hooks/src/framework.dart:133:12)
E/flutter (23009): #3      use (package:flutter_hooks/src/framework.dart:18:32)
E/flutter (23009): #4      useValueListenable (package:flutter_hooks/src/listenable.dart:9:3)
E/flutter (23009): #5      EditAgentVehiclesListScreen.build.<anonymous closure>.<anonymous closure> (package:pegasus_home/feature_tenancy/presentation/screen/edit_agent_vehicle_list_screen/edit_agent_vehicle_list_screen.dart:23:17)
E/flutter (23009): <asynchronous suspension>
```

Am I added it in the right place?

**Comment by tony123S** [comment]
fixed.

```
Widget _showBody(ValueNotifier<List<VehicleItems>> list) {
  final vehicleList = useValueListenable(list); // useValueListenable put here instead
  return ListView.separated(
      padding: EdgeInsets.zero,
      shrinkWrap: true,
      separatorBuilder: (context, index) => Padding(
          padding: const EdgeInsets.symmetric(horizontal: 20),
          child: Container(
            color: Colors.grey.shade200,
            height: 1,
          )),
      itemCount: vehicleList.length,
      itemBuilder: (context, index) {
        final items = vehicleList[index];
        return InkWell(
            onTap: () {},
            child: ListItemPadding(
              child: VehicleItem(items),
              // isDeleteVisible: false,
            ));
      });
}

```

**Comment by shahriarsihamstat** [comment]
> I have the same questions, useValueListenable is still not working for me when using `xx.value.add(1)` but `xx.value = [...xx.value, 1]` works

@soxft I had the same problem, and your solution worked for me as well. Kudos!
