### ISSUE TITLE
The following snippet causes an unclear error

### ISSUE THREAD

**Issue by modulovalue** [rrousselGit/flutter_hooks#98]
```dart
 return HookBuilder(
        builder: (context) {
            final state = useState(true);

            if (state.value)
                return HookBuilder(
                    builder: (context) {
                        return IconButton(
                            onPressed: () => state.value = !state.value,
                            icon: Icon(Icons.add),
                        );
                    },
                );
            else
                return HookBuilder(
                    builder: (context) {
                        final x = useState(1);
                        return IconButton(
                            onPressed: () => state.value = !state.value,
                            icon: Text(x.value.toString()),
                        );
                    },
                );
        },
    );
```
A tap on the button will cause the following error:
```
flutter: The following assertion was thrown building HookBuilder(dirty, state: _HookWidgetState#ee3db):
flutter: 'package:flutter_hooks/src/framework.dart': Failed assertion: line 375 pos 14: '_debugDidReassemble
flutter: || !_didFinishBuildOnce': is not true.
flutter: 
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter: 
flutter: Widget creation tracking is currently disabled. Enabling it enables improved error messages. It can
flutter: be enabled by passing `--track-widget-creation` to `flutter run` or `flutter test`.
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #2      HookElement._use (package:flutter_hooks/src/framework.dart:375:14)
flutter: #3      Hook.use (package:flutter_hooks/src/framework.dart:136:40)
flutter: #4      useState (package:flutter_hooks/src/primitives.dart:206:15)
flutter: #5      wPortfolioPage.<anonymous closure>.<anonymous closure> (package:neptune_portfolio_flutter/src/route_portfolio_page.dart:31:35)
flutter: #6      HookBuilder.build (package:flutter_hooks/src/framework.dart:544:41)
flutter: #7      _HookWidgetState.build (package:flutter_hooks/src/framework.dart:515:19)
flutter: #8      StatefulElement.build (package:flutter/src/widgets/framework.dart:4040:27)
flutter: #9      HookElement.build (package:flutter_hooks/src/framework.dart:276:26)
flutter: #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3934:15)
flutter: #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3731:5)
flutter: #12     StatefulElement.update (package:flutter/src/widgets/framework.dart:4113:5)
flutter: #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2886:15)
flutter: #14     HookElement.updateChild (package:flutter_hooks/src/framework.dart:334:18)
flutter: #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3954:16)
flutter: #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3731:5)
flutter: #17     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2341:33)
flutter: #18     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:761:20)
flutter: #19     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280:5)
flutter: #20     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1031:15)
flutter: #21     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:973:9)
flutter: #22     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:889:5)
flutter: #26     _invoke (dart:ui/hooks.dart:249:10)
flutter: #27     _drawFrame (dart:ui/hooks.dart:207:3)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter: 
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

The snippet doesn't make a lot of sense in this case but I need the use case where hookbuilders can be conditionally switched. 
I know that one solution is to give the hookbuilders a key but shouldn't this actually not throw any error at all?

**Comment by rrousselGit** [comment]
No, keys are required here.

Without them, switching between builders makes Flutter think that it should reuse the state of the previous builder instead of create a new state.

And since your builders have a different number of hooks, then the library throws because adding/removing hooks is not supported
